version: '3'
services:
  eureka-server:
    image: scservers/eureka-server
    container_name: sc-eureka-server
    restart: unless-stopped
    volumes:
      - ./data/eureka-server/logs:/var/logs
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - EUREKA_ZONE_HOST=eureka-server
    #depends_on:
      #- rabbitmq
    networks:
      - sc-net
    ports:
      - 8761:8761
  bus-server:
    image: scservers/bus-server
    container_name: sc-bus-server
    restart: unless-stopped
    volumes:
      - ./data/bus-server/logs:/var/logs
    depends_on:
      #- rabbitmq
      - eureka-server
    networks:
      - sc-net
    ports:
      - 8071:8071
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - EUREKA_ZONE_HOST=eureka-server
      - EUREKA_ZONE_PORT=8761
  config-server:
    image: scservers/config-server
    container_name: sc-config-server
    restart: unless-stopped
    volumes:
      - ./data/config-server/logs:/var/logs
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - EUREKA_ZONE_HOST=eureka-server
    depends_on:
      #- rabbitmq
      - eureka-server
    networks:
      - sc-net
    ports:
      - 8888:8888
networks:
  sc-net:
    driver: bridge