version: '3'
services:
  postgres-auth:
    image: postgres:9.6-alpine
    container_name: sc-postgres-auth
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./init/db:/docker-entrypoint-initdb.d
    networks:
      - sc-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  authorization-server:
    image: willen/authorization-server
    container_name: sc-authorization-server
    restart: unless-stopped
    volumes:
      - ./data/authorization-server/logs:/var/logs
    networks:
      - sc-net
    ports:
      - 7002:8000
    env_file: .env
    depends_on:
      - postgres-auth

  authentication-server:
    image: willen/authentication-server
    container_name: sc-authentication-server
    restart: unless-stopped
    volumes:
      - ./data/authentication-server/logs:/var/logs
    networks:
      - sc-net
    ports:
      - 7001:8001
    env_file: .env
    depends_on:
      - postgres-auth
networks:
  sc-net:
    driver: bridge