version: '3'
services:
  postgres-auth:
    image: postgres:9.6-alpine
    container_name: sc-postgres-auth
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./init/db:/docker-entrypoint-initdb.d
    networks:
      - sc-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
networks:
  sc-net:
    driver: bridge