version: '3'
services:
  authorization-server:
    image: scservers/authorization-server
    container_name: sc-authorization-server
    restart: unless-stopped
    volumes:
      - ./data/authorization-server/logs:/var/logs
    networks:
      - sc-net
    ports:
      - 7002:8000
    env_file: .env

  authentication-server:
    image: scservers/authentication-server
    container_name: sc-authentication-server
    restart: unless-stopped
    volumes:
      - ./data/authentication-server/logs:/var/logs
    networks:
      - sc-net
    ports:
      - 7001:8001
    env_file: .env
networks:
  sc-net:
    driver: bridge