version: '3'
services:
  center-demo:
    image: willen/center-demo
    container_name: sc-center-demo
    restart: unless-stopped
    volumes:
      - ./data/center-demo/logs:/var/logs
    #depends_on:
     # - rabbitmq
      #- eureka-server
      #- bus-server
      #- config-server
    networks:
      - sc-net
    ports:
      - 7091:8091
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - EUREKA_ZONE_HOST=eureka-server
      - EUREKA_ZONE_PORT=8761
networks:
  sc-net:
    driver: bridge