version: '3'
services:
  gateway-server:
    image: willen/gateway-server
    container_name: sc-gateway-server
    restart: unless-stopped
    volumes:
      - ./data/gateway-server/logs:/var/logs
    #depends_on:
     # - center-demo
    networks:
      - sc-net
    ports:
      - 7073:8073
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - EUREKA_ZONE_HOST=eureka-server
      - EUREKA_ZONE_PORT=8761
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
networks:
  sc-net:
    driver: bridge