#eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}:@project.version@
eureka:
  # 生产环境中官方是不建议修改默认配置，因为那样会破坏 eureka server 的保护模式
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
# 开启Feign Hystrix 支持 
feign: 
  hystrix:
    enabled: true
# hystrix endpoint ：http://localhost:port/actuator/hystrix.stream
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        # 如果嫌麻烦，可以一次性加载所有的
        # include: '*'
        include: 'hystrix.stream'
