server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: config-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true #开启config服务发现，既开启集群环境，此开关开启时，client必须使用服务名链接config server。
      server:
        git:
          uri: https://github.com/willenchou/scserver-config.git
          searchPaths: /center-config
management:
  endpoints:
    web:
      exposure:
        include: '*'